config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :companies do
    patch 'refresh_token', to: 'companies#refresh_token'
    resources :payment_methods do
      resources :discounts, only: %i[show new create]
    end
    resources :products, only: %i[show new create]
  end
  resources :payments do
    patch 'activate', to: 'payments#activate'
    patch 'inactivate', to: 'payments#inactivate'
  end

  resources :charges
  get 'search', to:"charges#search"

  namespace :api do
    namespace :v1 do
      resources :clients do
        patch 'generate_token', to: 'clients#generate_token'
      end
      resources :charges
      get 'search_by_expiration_date', to:"charges#search_by_expiration_date"
      get 'search_by_payment_method', to:"charges#search_by_payment_method"
    end
  end

end

app/models/payment_method.rb
require 'securerandom'
class PaymentMethod < ApplicationRecord
  belongs_to :payment
  belongs_to :company
  before_create :adjust_blank_fields

  def display_name
    "#{payment.name} - #{payment.type_payment}"
  end

  def send_payment_confirmation
    SecureRandom.hex(10)
  end

  private

  def adjust_blank_fields
    if Payment.find(payment_id).type_payment == 'pix' || Payment.find(payment_id).type_payment == 'credito'
      self.agency = '000'
      self.bank_account = '000'
    end
  end
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  def index
    @payment_method = PaymentMethod.all
  end

  def show
    @payment_method = PaymentMethod.find(params[:id])
  end

  def new
    @payments = Payment.all
    @payment_method = PaymentMethod.new
  end

  def create
    @payment_method = PaymentMethod.new(payment_method_params)
    @payment_method.company_id = params[:company_id]
    if @payment_method.save
      # byebug
      redirect_to company_payment_method_path(params[:company_id],
                                              @payment_method)
    else
      @payment = Payment.all
      render :new
    end
  end

  private

  def payment_method_params
    params.require(:payment_method).permit(:payment_id, :code, :agency,
                                           :bank_account)
  end
end

app/views/payment_methods/_form.html.erb
<%= form_with model: payment_method, url: company_payment_methods_path do |f| %>
  <%= f.label :payment_id, 'Tipo de Pagamento' %>
  <%= f.collection_select :payment_id, payments, :id, :display_name %>
  <%= f.label :code, 'Chave' %>
  <%= f.text_field :code %>
  <div id='bank'>
    <%= f.label :agency, 'Agência' %>
    <%= f.text_field :agency%>
    <%= f.label :bank_account, 'Número da conta'%>
    <%= f.text_field :bank_account%>
  </div>
  <%= f.submit button_text %>
<%end%>

app/views/payment_methods/new.html.erb
<h1>Nova Forma de Pagamento</h1>

<%= render 'form', payment_method: @payment_method, payments: @payments, button_text: 'Salvar' %>

app/views/payment_methods/show.html.erb
<h1>Pagamentos Cadastrados para a Empresa</h1>
<dl>
  <dt>Pagamento</dt>
  <dd><%= @payment_method.payment.name %> - <%= @payment_method.payment.type_payment %></dd>
  <dt>Código de transação</dt>
  <dd><%= @payment_method.code %></dd>
  <dt>Código do Banco</dt>
  <dd><%= @payment_method.payment.bank_code == '000' ? 'não precisa' : @payment_method.payment.bank_code %></dd>
  <dt>Número da Agência</dt>
  <dd><%= @payment_method.agency == '000' ? 'não precisa' : @payment_method.agency %></dd>
  <dt>Número da Conta Bancária</dt>
  <dd><%= @payment_method.bank_account == '000' ? 'não precisa' : @payment_method.bank_account %></dd>
</dl>

<%= link_to 'Aplicar desconto para Forma de Pagamento', new_company_payment_method_discount_path(@payment_method.company, @payment_method)%>