config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :companies do
    patch 'refresh_token', to: 'companies#refresh_token'
    resources :payment_methods do
      resources :discounts, only: %i[show new create]
    end
    resources :products, only: %i[show new create]
  end
  resources :payments do
    patch 'activate', to: 'payments#activate'
    patch 'inactivate', to: 'payments#inactivate'
  end

  resources :charges
  get 'search', to:"charges#search"

  namespace :api do
    namespace :v1 do
      resources :clients do
        patch 'generate_token', to: 'clients#generate_token'
      end
      resources :charges
      get 'search_by_expiration_date', to:"charges#search_by_expiration_date"
      get 'search_by_payment_method', to:"charges#search_by_payment_method"
    end
  end

end

app/models/company.rb
require 'securerandom'
class Company < ApplicationRecord
  audited
  validates :name, :cnpj, :email, :address, presence: true
  before_create :generate_token

  def refresh_token!
    generate_token
    save
  end

  private

  def generate_token
    self.token = SecureRandom.hex(20)
    generate_token if Company.exists?(token: self.token)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to @company
    else
      render :new
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to @company
    else
      render :edit
    end
  end

  def refresh_token
    @company = Company.find(params[:company_id])
    if @company.refresh_token!
      redirect_to @company, notice: 'Token atualizado com sucesso'
    else
      render :show, notice: 'Erro ao atualizar o Token'
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :cnpj, :address, :email)
  end
end

app/views/companies/_form.html.erb
<% if company.errors.any? %>
  <p>Foram encontrados <%= company.errors.count %> erro(s):</p>
  <ul>
    <% company.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: company do |f| %>
  <%= f.label :name%>
  <%= f.text_field :name %>
  <%= f.label :cnpj%>
  <%= f.text_field :cnpj %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit button_text %>
<% end %>

app/views/companies/edit.html.erb
<h1>Atualizar uma Empresa</h1>

<%= render 'form', company: @company, button_text: 'Salvar' %>

app/views/companies/index.html.erb
<% if @companies.empty? %>
  <p><%= "Nenhuma Empresa cadastrada" %> </p>
<% else %>
  <dl>
  <% @companies.each do |company| %>
    <dt>Nome: </dt>
    <dd> <%= link_to company.name, company_path(company.id) %> </dd>
    <dt>Endereço: </dt>
    <dd> <%= company.address %> </dd>
    <dt>Email: </dt>
    <dd> <%= company.email %> </dd>
  <% end %>
  </dl>
<% end %>
<%= link_to "Registrar uma Empresa", new_company_path %>
<%= link_to "Voltar Para a página Inicial", root_path %>

app/views/companies/new.html.erb
<h1>Nova Empresa</h1>

<%= render 'form', company: @company, button_text: 'Criar Empresa' %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>
<dl>
  <dt>CNPJ</dt>
  <dd><%= @company.cnpj %></dd>
  <dt>Endereço de Faturamento</dt>
  <dd><%= @company.address %></dd>
  <dt>E-mail para Faturamento</dt>
  <dd><%= @company.email %></dd>
  <dt>Token</dt>
  <dd><%= @company.token %></dd>
</dl>

<%if current_user && current_user.administrator_paynow?%>
  <%= link_to 'Atualizar Token', company_refresh_token_path(@company), method: :patch %>
  <%= link_to 'Editar', edit_company_path(@company) %>
<%end%>
<%= link_to 'Adicionar Método de Pagamento', new_company_payment_method_path(@company)%>
<%= link_to 'Adicionar produto', new_company_product_path(@company) %>
<%= link_to 'Voltar', root_path %>