config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :companies do
    patch 'refresh_token', to: 'companies#refresh_token'
    resources :payment_methods do
      resources :discounts, only: %i[show new create]
    end
    resources :products, only: %i[show new create]
  end
  resources :payments do
    patch 'activate', to: 'payments#activate'
    patch 'inactivate', to: 'payments#inactivate'
  end

  resources :charges
  get 'search', to:"charges#search"

  namespace :api do
    namespace :v1 do
      resources :clients do
        patch 'generate_token', to: 'clients#generate_token'
      end
      resources :charges
      get 'search_by_expiration_date', to:"charges#search_by_expiration_date"
      get 'search_by_payment_method', to:"charges#search_by_payment_method"
    end
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  validates :name, :type_payment, :fee_percentage, :max_fee, presence: true
  validates :bank_code, length: { maximum: 3 }
  enum type_payment: { pix: 5, boleto: 10, credito: 15 }
  has_one_attached :logo
  before_create :set_bank_to_credit

  def display_name
    "#{name} - #{type_payment}"
  end

  private

  def set_bank_to_credit
    self.bank_code = '000' if type_payment == 'credito'
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @payments = Payment.all
  end

  def show
    @payment = Payment.find(params[:id])
  end

  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new(payment_params)
    if @payment.save
      # byebug
      @payment.active = true
      redirect_to @payment
    else
      render :new
    end
  end

  def edit
    @payment = Payment.find(params[:id])
  end

  def update
    @payment = Payment.find(params[:id])

    if @payment.update(payment_params)
      redirect_to @payment
    else
      render :edit
    end
  end

  def activate
    @payment = Payment.find(params[:payment_id])
    if @payment.update(active: true)
      redirect_to payment_path(@payment)
    else
      render :index
    end
  end

  def inactivate
    @payment = Payment.find(params[:payment_id])
    if @payment.update(active: false)
      redirect_to payment_path(@payment)
    else
      render :index
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:name, :type_payment, :fee_percentage,
                                    :max_fee, :logo, :bank_code)
  end
end

app/views/payments/_form.html.erb
<% if payment.errors.any? %>
  <p>Foram encontrados <%= payment.errors.count %> erro(s):</p>
  <ul>
    <% payment.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: payment do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :type_payment %>
  <%= f.select :type_payment, Payment.type_payments.keys %>
  <%= f.label :bank_code, style: "#{'display:none' if payment.type_payment == 'credito'}" %>
  <%= f.text_field :bank_code, style: "#{'display:none' if payment.type_payment == 'credito'}" %>
  <%= f.label :fee_percentage %>
  <%= f.number_field :fee_percentage %>
  <%= f.label :max_fee %>
  <%= f.number_field :max_fee %>
  <%= f.label :logo %>
  <%= f.file_field :logo %>
  <%= f.submit button_text %>
<% end %>

app/views/payments/edit.html.erb
<h1>Atualizar uma Forma de Pagamento</h1>

<%= render 'form', payment: @payment, button_text: 'Salvar' %>

app/views/payments/index.html.erb
<% if @payments.empty? %>
  <p><%= "Nenhuma forma de pagamento cadastrada" %> </p>
<% else %>
  <dl>
  <% @payments.each do |payment| %>
    <dt>Nome: </dt>
    <dd> <%= link_to payment.name, payment_path(payment.id) %> </dd>
    <dt>Tipo: </dt>
    <dd> <%= payment.type %> </dd>
    <dt>Taxa por Cobrança: </dt>
    <dd> <%= payment.fee_percentage %> </dd>
    <dt>Taxa máxima (R$): </dt>
    <dd> <%= payment.max_fee %> </dd>
    <dt>Status: </dt>
    <dd> <%= payment.active ? 'Ativo' : 'Inativo' %> </dd>
  <% end %>
  </dl>
<% end %>
<%= link_to "Registrar uma Forma de Pagamento", new_payment_path %>
<%= link_to "Voltar Para a página Inicial", root_path %>

app/views/payments/new.html.erb
<h1>Nova Forma de Pagamento</h1>

<%= render 'form', payment: @payment, button_text: 'Criar Forma de Pagamento' %>

app/views/payments/show.html.erb
<% if @payment.logo.attached? %>
  <%= image_tag @payment.logo %>
<% end %>
<h1><%= @payment.name %></h1>
<dl>
  <dt>Tipo de Pagamento</dt>
  <dd><%= @payment.type_payment %></dd>
  <dt>Taxa por Cobrança</dt>
  <dd><%= number_to_percentage(@payment.fee_percentage, delimiter: ',', precision: 1) %></dd>
  <dt>Taxa máxima (R$)</dt>
  <dd><%= number_to_currency @payment.max_fee %></dd>
  <dt>Status</dt>
  <dd><%= @payment.active ? 'Ativo' : 'Inativo' %></dd>
</dl>

<% if @payment.active? %>
  <%= link_to 'Inativar', payment_inactivate_path(@payment.id), method: :patch%>
<%else%>
  <%= link_to 'Ativar', payment_activate_path(@payment.id), method: :patch%>
<%end%>

<%= link_to 'Editar', edit_payment_path(@payment) %>
<%= link_to 'Voltar', root_path %>