config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :companies do
    patch 'refresh_token', to: 'companies#refresh_token'
    resources :payment_methods do
      resources :discounts, only: %i[show new create]
    end
    resources :products, only: %i[show new create]
  end
  resources :payments do
    patch 'activate', to: 'payments#activate'
    patch 'inactivate', to: 'payments#inactivate'
  end

  resources :charges
  get 'search', to:"charges#search"

  namespace :api do
    namespace :v1 do
      resources :clients do
        patch 'generate_token', to: 'clients#generate_token'
      end
      resources :charges
      get 'search_by_expiration_date', to:"charges#search_by_expiration_date"
      get 'search_by_payment_method', to:"charges#search_by_payment_method"
    end
  end

end

app/models/charge.rb
require 'securerandom'
class Charge < ApplicationRecord
  belongs_to :company
  belongs_to :product
  belongs_to :payment_method
  belongs_to :client
  belongs_to :discount
  enum status: { pendente: 5, aprovada: 10, rejeitada: 15 }
  before_create :generate_token

  private

  def generate_token
    self.token = SecureRandom.hex(20)
  end
end

app/controllers/api/v1/charges_controller.rb
class Api::V1::ChargesController < ActionController::API
  def create
    @charge = Charge.new(charge_params)
    if @charge.save!
      render json: @charge, status: :created
    else
      render json: { status: 'error', code: 3000,
                     message: 'Error on create charge' }
    end
  rescue ActionController::ParameterMissing
    render status: :precondition_failed,
           json: { errors: 'parâmetros inválidos' }
  end

  def search_by_expiration_date
    @charges = Charge.where('expiration_date like ?', "%#{params[:q]}%")
    render json: @charges
  end

  def search_by_payment_method
    @charges = Charge.where('payment_method_id like ?', "%#{params[:q]}%")
    render json: @charges
  end

  private

  def charge_params
    params
      .require(:charge)
      .permit(:company_id, :product_id, :payment_method_id, :client_id, :discount_id,
              :card_name, :card_number, :card_code, :original_price, :new_price, :status, :boleto_address)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def index
    @charges = Charge.all
  end

  def show
    @charge = Charge.find(params[:id])
  end

  def new
    @charge = Charge.new
  end

  def edit
    @charge = Charge.find(params[:id])
  end

  def update
    @charge = Charge.find(params[:id])

    if @charge.update(charge_params) && @charge.status == 'aprovada'
      @charge.payment_confirmation = @charge.payment_method.send_payment_confirmation
      @charge.update(charge_params)
      redirect_to charge_path(@charge)
    elsif @charge.update(charge_params) && @charge.status == 'pendente'
      redirect_to root_path
    else
      render :edit
    end
  end

  def search
    @charges = Charge.where('expiration_date like ?', "%#{params[:q]}%")
    # byebug
  end

  private

  def charge_params
    params
      .require(:charge)
      .permit(:company_id, :product_id, :payment_method_id, :client_id, :discount_id,
              :card_name, :card_number, :card_code, :original_price, :payment_confirmation, :new_price, :status, :boleto_address, :date_payment, :expiration_date, :bank_code_error)
  end
end

app/views/charges/_form.html.erb
<%= form_with model: @charge do |f| %>
  <%= f.radio_button :status, "aprovada" %>
  <%= f.label :status_aprovada, "Aprovar" %>
  <%= f.radio_button :status, "pendente" %>
  <%= f.label :status_rejeitada, "Rejeitar" %>
  <%= f.label :date_payment, 'Data efetiva da operação'%>
  <%= f.text_field :date_payment %>
  <%= f.label :bank_code_error, 'Código de erro'%>
  <%= f.text_field :bank_code_error %>
  <%= f.submit 'Salvar' %>
<%end%>

app/views/charges/edit.html.erb
<h1>Alterar Status da Cobrança</h1>

<%= render 'form', company: @charge%>

app/views/charges/index.html.erb
<h1>Buscar cobranças</h1>

<%= form_with url: search_path, method: :get do %>
    <%= radio_button_tag :q, 30.days.ago.to_date %>
    <%= label_tag :"#{30.days.ago.to_date}", '30 dias atrás' %>
    
    <%= radio_button_tag :q, 90.days.ago.to_date %>
    <%= label_tag :"#{90.days.ago.to_date}", '90 dias atrás' %>
    
    <%= radio_button_tag :q, '1' %>
    <%= label_tag :q_1, 'Histórico completo' %>
    
    <%= submit_tag 'Pesquisar' %>
  <% end %>

<h1>Todas as Cobranças</h1>

<dl>

<%@charges.each do |charge|%>
 
  
    <dt>Produto: </dt>
    <dd><%= charge.product.name %> </dd>
    <dt>Status: </dt>
    <dd><%= charge.status %> </dd>
    <dt>Valor com desconto (R$): </dt>
    <dd><%= number_to_currency charge.new_price %> </dd>
    
    <dt> <%= link_to 'Alterar Status da Cobrança', edit_charge_path(charge.id) %> </dt>
    
<%end%>
</dl>

app/views/charges/search.html.erb
<h1>Resultado da busca</h1>
  
<dl>
  <% @charges.each do |charge| %>
    <dt>Nome do produto</dt>
    <dd><%= charge.product.name %></dd>
    
    <dt>Nome do cliente</dt>
    <dd><%= charge.client.name %></dd>
    
    <dt>Data de Vencimento</dt>
    <dd><%= charge.expiration_date %></dd>
    
    <dt>Status</dt>
    <dd><%= charge.status %></dd>
    
  <% end %>
</dl>

app/views/charges/show.html.erb
<h1>Recibo de Compra</h1>

<dl>
  <dt>Produto</dt>
  <dd><%= @charge.product.name %></dd>
  <dt>Data de vencimento da cobrança</dt>
  <dd><%= @charge.expiration_date.strftime( '%d/%m/%Y') %></dd>
  <dt>Data de Pagamento</dt>
  <dd><%= @charge.date_payment.strftime( '%d/%m/%Y') %></dd>
  <dt>Código de Autorização</dt>
  <dd><%= @charge.payment_confirmation %></dd>
</dl>